name: Self-hosted runner (past-ci-caller)

on:
  push:
    branches:
      - run-past-ci*

jobs:
  run_past_ci_pytorch_1-4:
    name: PyTorch 1.4
    if: always()
    uses: ./.github/workflows/self-past.yml
    with:
      framework: pytorch
      version: "1.4"
    secrets: inherit
